DROP TABLE IF EXISTS comments  CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar UNIQUE NOT NULL
);

CREATE TABLE requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description varchar NOT NULL,
  requestor_id bigint NOT NULL,
  created TIMESTAMP NOT NULL
);

CREATE TABLE items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar NOT NULL,
  is_available boolean NOT NULL,
  owner_id bigint NOT NULL,
  request_id bigint
);

CREATE TABLE bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  item_id bigint NOT NULL,
  booker_id bigint NOT NULL,
  status varchar NOT NULL
);

CREATE TABLE comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text varchar NOT NULL,
  item_id bigint NOT NULL,
  author_id bigint NOT NULL,
  created TIMESTAMP NOT NULL
);

COMMENT ON TABLE users IS 'Пользователи';

COMMENT ON COLUMN users.id IS 'ИД';

COMMENT ON COLUMN users.name IS 'Имя пользователя';

COMMENT ON COLUMN users.email IS 'Email пользователя';

COMMENT ON TABLE items IS 'Вещи';

COMMENT ON COLUMN items.id IS 'ИД';

COMMENT ON COLUMN items.name IS 'Наименование вещи';

COMMENT ON COLUMN items.description IS 'Описание вещи';

COMMENT ON COLUMN items.is_available IS 'Доступность';

COMMENT ON COLUMN items.owner_id IS 'ИД владельца';

COMMENT ON COLUMN items.request_id IS 'ИД запроса на создание';

COMMENT ON TABLE bookings IS 'Бронирования';

COMMENT ON COLUMN bookings.id IS 'ИД';

COMMENT ON COLUMN bookings.start_date IS 'Время начала';

COMMENT ON COLUMN bookings.end_date IS 'Время окончания';

COMMENT ON COLUMN bookings.item_id IS 'ИД вещи';

COMMENT ON COLUMN bookings.booker_id IS 'ИД пользователя';

COMMENT ON TABLE requests IS 'Запросы на создание';

COMMENT ON COLUMN requests.id IS 'ИД';

COMMENT ON COLUMN requests.description IS 'Описание вещи';

COMMENT ON COLUMN requests.requestor_id IS 'ИД создателя';

COMMENT ON COLUMN comments.id IS 'ИД';

COMMENT ON COLUMN comments.text IS 'Текст комментария';

COMMENT ON COLUMN comments.item_id IS 'ИД вещи';

COMMENT ON COLUMN comments.author_id IS 'ИД автора';

COMMENT ON COLUMN comments.created IS 'Время создания';

ALTER TABLE items ADD CONSTRAINT fk_items_users FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE items ADD CONSTRAINT fk_items_requests FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE SET NULL;

ALTER TABLE bookings ADD CONSTRAINT fk_bookings_items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT;

ALTER TABLE bookings ADD CONSTRAINT fk_bookings_users FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE requests ADD CONSTRAINT fk_requests_users FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE RESTRICT;

ALTER TABLE comments ADD CONSTRAINT fk_comments_items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE;

ALTER TABLE comments ADD CONSTRAINT fk_comments_users FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;
